
// const NGU_TARGET = 'target'
// const NGU_PERCENTAGE = 'percentage'
// const NGU_TIME = 'time'
// const NGU_VALUE = 'value'



export const nguValueElts = [
    'energyNGUAugmentsValue',
    'energyNGUWandoosValue',
    'energyNGURespawnValue',
    'energyNGUGoldValue',
    'energyNGUAdventureAValue',
    'energyNGUPowerAValue',
    'energyNGUDropChanceValue',
    'energyNGUMagicNGUValue',
    'energyNGUPPValue',
    'magicNGUYggdrasilValue',
    'magicNGUExpValue',
    'magicNGUPowerBValue',
    'magicNGUNumberValue',
    'magicNGUTimeMachineValue',
    'magicNGUEnergyNGUValue',
    'magicNGUAdventureBValue',

    'energyNGUAugmentsEvilValue',
    'energyNGUWandoosEvilValue',
    'energyNGURespawnEvilValue',
    'energyNGUGoldEvilValue',
    'energyNGUAdventureAEvilValue',
    'energyNGUPowerAEvilValue',
    'energyNGUDropChanceEvilValue',
    'energyNGUMagicNGUEvilValue',
    'energyNGUPPEvilValue',
    'magicNGUYggdrasilEvilValue',
    'magicNGUExpEvilValue',
    'magicNGUPowerBEvilValue',
    'magicNGUNumberEvilValue',
    'magicNGUTimeMachineEvilValue',
    'magicNGUEnergyNGUEvilValue',
    'magicNGUAdventureBEvilValue',

    'energyNGUAugmentsSadisticValue',
    'energyNGUWandoosSadisticValue',
    'energyNGURespawnSadisticValue',
    'energyNGUGoldSadisticValue',
    'energyNGUAdventureASadisticValue',
    'energyNGUPowerASadisticValue',
    'energyNGUDropChanceSadisticValue',
    'energyNGUMagicNGUSadisticValue',
    'energyNGUPPSadisticValue',
    'magicNGUYggdrasilSadisticValue',
    'magicNGUExpSadisticValue',
    'magicNGUPowerBSadisticValue',
    'magicNGUNumberSadisticValue',
    'magicNGUTimeMachineSadisticValue',
    'magicNGUEnergyNGUSadisticValue',
    'magicNGUAdventureBSadisticValue',
]

export const nguTargetElts = [
    'energyNGUAugmentsTarget',
    'energyNGUWandoosTarget',
    'energyNGURespawnTarget',
    'energyNGUGoldTarget',
    'energyNGUAdventureATarget',
    'energyNGUPowerATarget',
    'energyNGUDropChanceTarget',
    'energyNGUMagicNGUTarget',
    'energyNGUPPTarget',
    'magicNGUYggdrasilTarget',
    'magicNGUExpTarget',
    'magicNGUPowerBTarget',
    'magicNGUNumberTarget',
    'magicNGUTimeMachineTarget',
    'magicNGUEnergyNGUTarget',
    'magicNGUAdventureBTarget',

    'energyNGUAugmentsEvilTarget',
    'energyNGUWandoosEvilTarget',
    'energyNGURespawnEvilTarget',
    'energyNGUGoldEvilTarget',
    'energyNGUAdventureAEvilTarget',
    'energyNGUPowerAEvilTarget',
    'energyNGUDropChanceEvilTarget',
    'energyNGUMagicNGUEvilTarget',
    'energyNGUPPEvilTarget',
    'magicNGUYggdrasilEvilTarget',
    'magicNGUExpEvilTarget',
    'magicNGUPowerBEvilTarget',
    'magicNGUNumberEvilTarget',
    'magicNGUTimeMachineEvilTarget',
    'magicNGUEnergyNGUEvilTarget',
    'magicNGUAdventureBEvilTarget',

    'energyNGUAugmentsSadisticTarget',
    'energyNGUWandoosSadisticTarget',
    'energyNGURespawnSadisticTarget',
    'energyNGUGoldSadisticTarget',
    'energyNGUAdventureASadisticTarget',
    'energyNGUPowerASadisticTarget',
    'energyNGUDropChanceSadisticTarget',
    'energyNGUMagicNGUSadisticTarget',
    'energyNGUPPSadisticTarget',
    'magicNGUYggdrasilSadisticTarget',
    'magicNGUExpSadisticTarget',
    'magicNGUPowerBSadisticTarget',
    'magicNGUNumberSadisticTarget',
    'magicNGUTimeMachineSadisticTarget',
    'magicNGUEnergyNGUSadisticTarget',
    'magicNGUAdventureBSadisticTarget',
]