
const NGU_TARGET = 'target'
const NGU_PERCENTAGE = 'percentage'
const NGU_TIME = 'time'
const NGU_VALUE = 'value'


export var nguInfoNameChanges = {
    'energyNGUAugmentsLevel': 'Augments Level',
    'energyNGUWandoosLevel': 'Wandoos Level',
    'energyNGURespawnLevel': 'Respawn Level',
    'energyNGUGoldLevel': 'Gold Level',
    'energyNGUAdventureALevel': 'Adventure α Level',
    'energyNGUPowerALevel': 'Power α Level',
    'energyNGUDropChanceLevel': 'Drop Chance Level',
    'energyNGUMagicNGULevel': 'Magic NGU Level',
    'energyNGUPPLevel': 'PP Level',
    'magicNGUYggdrasilLevel': 'Yggdrasil Level',
    'magicNGUExpLevel': 'Exp Level',
    'magicNGUPowerBLevel': 'Power β Level',
    'magicNGUNumberLevel': 'Number Level',
    'magicNGUTimeMachineLevel': 'Time Machine Level',
    'magicNGUEnergyNGULevel': 'Energy NGU Level',
    'magicNGUAdventureBLevel': 'Adventure β Level',
    'energyNGUAugmentsTarget': 'Augments Target',
    'energyNGUWandoosTarget': 'Wandoos Target',
    'energyNGURespawnTarget': 'Respawn Target',
    'energyNGUGoldTarget': 'Gold Target',
    'energyNGUAdventureATarget': 'Adventure α Target',
    'energyNGUPowerATarget': 'Power α Target',
    'energyNGUDropChanceTarget': 'Drop Chance Target',
    'energyNGUMagicNGUTarget': 'Magic NGU Target',
    'energyNGUPPTarget': 'PP Target',
    'magicNGUYggdrasilTarget': 'Yggdrasil Target',
    'magicNGUExpTarget': 'Exp Target',
    'magicNGUPowerBTarget': 'Power β Target',
    'magicNGUNumberTarget': 'Number Target',
    'magicNGUTimeMachineTarget': 'Time Machine Target',
    'magicNGUEnergyNGUTarget': 'Energy NGU Target',
    'magicNGUAdventureBTarget': 'Adventure β Target',

    'energyNGUAugmentsEvilLevel': 'Augments Level',
    'energyNGUWandoosEvilLevel': 'Wandoos Level',
    'energyNGURespawnEvilLevel': 'Respawn Level',
    'energyNGUGoldEvilLevel': 'Gold Level',
    'energyNGUAdventureAEvilLevel': 'Adventure α Level',
    'energyNGUPowerAEvilLevel': 'Power α Level',
    'energyNGUDropChanceEvilLevel': 'Drop Chance Level',
    'energyNGUMagicNGUEvilLevel': 'Magic NGU Level',
    'energyNGUPPEvilLevel': 'PP Level',
    'magicNGUYggdrasilEvilLevel': 'Yggdrasil Level',
    'magicNGUExpEvilLevel': 'Exp Level',
    'magicNGUPowerBEvilLevel': 'Power β Level',
    'magicNGUNumberEvilLevel': 'Number Level',
    'magicNGUTimeMachineEvilLevel': 'Time Machine Level',
    'magicNGUEnergyNGUEvilLevel': 'Energy NGU Level',
    'magicNGUAdventureBEvilLevel': 'Adventure β Level',
    'energyNGUAugmentsEvilTarget': 'Augments Target',
    'energyNGUWandoosEvilTarget': 'Wandoos Target',
    'energyNGURespawnEvilTarget': 'Respawn Target',
    'energyNGUGoldEvilTarget': 'Gold Target',
    'energyNGUAdventureAEvilTarget': 'Adventure α Target',
    'energyNGUPowerAEvilTarget': 'Power α Target',
    'energyNGUDropChanceEvilTarget': 'Drop Chance Target',
    'energyNGUMagicNGUEvilTarget': 'Magic NGU Target',
    'energyNGUPPEvilTarget': 'PP Target',
    'magicNGUYggdrasilEvilTarget': 'Yggdrasil Target',
    'magicNGUExpEvilTarget': 'Exp Target',
    'magicNGUPowerBEvilTarget': 'Power β Target',
    'magicNGUNumberEvilTarget': 'Number Target',
    'magicNGUTimeMachineEvilTarget': 'Time Machine Target',
    'magicNGUEnergyNGUEvilTarget': 'Energy NGU Target',
    'magicNGUAdventureBEvilTarget': 'Adventure β Target',

    'energyNGUAugmentsSadisticLevel': 'Augments Level',
    'energyNGUWandoosSadisticLevel': 'Wandoos Level',
    'energyNGURespawnSadisticLevel': 'Respawn Level',
    'energyNGUGoldSadisticLevel': 'Gold Level',
    'energyNGUAdventureASadisticLevel': 'Adventure α Level',
    'energyNGUPowerASadisticLevel': 'Power α Level',
    'energyNGUDropChanceSadisticLevel': 'Drop Chance Level',
    'energyNGUMagicNGUSadisticLevel': 'Magic NGU Level',
    'energyNGUPPSadisticLevel': 'PP Level',
    'magicNGUYggdrasilSadisticLevel': 'Yggdrasil Level',
    'magicNGUExpSadisticLevel': 'Exp Level',
    'magicNGUPowerBSadisticLevel': 'Power β Level',
    'magicNGUNumberSadisticLevel': 'Number Level',
    'magicNGUTimeMachineSadisticLevel': 'Time Machine Level',
    'magicNGUEnergyNGUSadisticLevel': 'Energy NGU Level',
    'magicNGUAdventureBSadisticLevel': 'Adventure β Level',
    'energyNGUAugmentsSadisticTarget': 'Augments Target',
    'energyNGUWandoosSadisticTarget': 'Wandoos Target',
    'energyNGURespawnSadisticTarget': 'Respawn Target',
    'energyNGUGoldSadisticTarget': 'Gold Target',
    'energyNGUAdventureASadisticTarget': 'Adventure α Target',
    'energyNGUPowerASadisticTarget': 'Power α Target',
    'energyNGUDropChanceSadisticTarget': 'Drop Chance Target',
    'energyNGUMagicNGUSadisticTarget': 'Magic NGU Target',
    'energyNGUPPSadisticTarget': 'PP Target',
    'magicNGUYggdrasilSadisticTarget': 'Yggdrasil Target',
    'magicNGUExpSadisticTarget': 'Exp Target',
    'magicNGUPowerBSadisticTarget': 'Power β Target',
    'magicNGUNumberSadisticTarget': 'Number Target',
    'magicNGUTimeMachineSadisticTarget': 'Time Machine Target',
    'magicNGUEnergyNGUSadisticTarget': 'Energy NGU Target',
    'magicNGUAdventureBSadisticTarget': 'Adventure β Target',
}

export var nguExtraNameChanges = {
    'energyNGUAugmentsValue': 'Augments Value',
    'energyNGUWandoosValue': 'Wandoos Value',
    'energyNGURespawnValue': 'Respawn Value',
    'energyNGUGoldValue': 'Gold Value',
    'energyNGUAdventureAValue': 'Adventure α Value',
    'energyNGUPowerAValue': 'Power α Value',
    'energyNGUDropChanceValue': 'Drop Chance Value',
    'energyNGUMagicNGUValue': 'Magic NGU Value',
    'energyNGUPPValue': 'PP Value',
    'magicNGUYggdrasilValue': 'Yggdrasil Value',
    'magicNGUExpValue': 'Exp Value',
    'magicNGUPowerBValue': 'Power β Value',
    'magicNGUNumberValue': 'Number Value',
    'magicNGUTimeMachineValue': 'Time Machine Value',
    'magicNGUEnergyNGUValue': 'Energy NGU Value',
    'magicNGUAdventureBValue': 'Adventure β Value',

    'energyNGUAugmentsEvilValue': 'Augments Value',
    'energyNGUWandoosEvilValue': 'Wandoos Value',
    'energyNGURespawnEvilValue': 'Respawn Value',
    'energyNGUGoldEvilValue': 'Gold Value',
    'energyNGUAdventureAEvilValue': 'Adventure α Value',
    'energyNGUPowerAEvilValue': 'Power α Value',
    'energyNGUDropChanceEvilValue': 'Drop Chance Value',
    'energyNGUMagicNGUEvilValue': 'Magic NGU Value',
    'energyNGUPPEvilValue': 'PP Value',
    'magicNGUYggdrasilEvilValue': 'Yggdrasil Value',
    'magicNGUExpEvilValue': 'Exp Value',
    'magicNGUPowerBEvilValue': 'Power β Value',
    'magicNGUNumberEvilValue': 'Number Value',
    'magicNGUTimeMachineEvilValue': 'Time Machine Value',
    'magicNGUEnergyNGUEvilValue': 'Energy NGU Value',
    'magicNGUAdventureBEvilValue': 'Adventure β Value',

    'energyNGUAugmentsSadisticValue': 'Augments Value',
    'energyNGUWandoosSadisticValue': 'Wandoos Value',
    'energyNGURespawnSadisticValue': 'Respawn Value',
    'energyNGUGoldSadisticValue': 'Gold Value',
    'energyNGUAdventureASadisticValue': 'Adventure α Value',
    'energyNGUPowerASadisticValue': 'Power α Value',
    'energyNGUDropChanceSadisticValue': 'Drop Chance Value',
    'energyNGUMagicNGUSadisticValue': 'Magic NGU Value',
    'energyNGUPPSadisticValue': 'PP Value',
    'magicNGUYggdrasilSadisticValue': 'Yggdrasil Value',
    'magicNGUExpSadisticValue': 'Exp Value',
    'magicNGUPowerBSadisticValue': 'Power β Value',
    'magicNGUNumberSadisticValue': 'Number Value',
    'magicNGUTimeMachineSadisticValue': 'Time Machine Value',
    'magicNGUEnergyNGUSadisticValue': 'Energy NGU Value',
    'magicNGUAdventureBSadisticValue': 'Adventure β Value',
}


export var nguValueElts = [
    'energyNGUAugmentsValue',
    'energyNGUWandoosValue',
    'energyNGURespawnValue',
    'energyNGUGoldValue',
    'energyNGUAdventureAValue',
    'energyNGUPowerAValue',
    'energyNGUDropChanceValue',
    'energyNGUMagicNGUValue',
    'energyNGUPPValue',
    'magicNGUYggdrasilValue',
    'magicNGUExpValue',
    'magicNGUPowerBValue',
    'magicNGUNumberValue',
    'magicNGUTimeMachineValue',
    'magicNGUEnergyNGUValue',
    'magicNGUAdventureBValue',

    'energyNGUAugmentsEvilValue',
    'energyNGUWandoosEvilValue',
    'energyNGURespawnEvilValue',
    'energyNGUGoldEvilValue',
    'energyNGUAdventureAEvilValue',
    'energyNGUPowerAEvilValue',
    'energyNGUDropChanceEvilValue',
    'energyNGUMagicNGUEvilValue',
    'energyNGUPPEvilValue',
    'magicNGUYggdrasilEvilValue',
    'magicNGUExpEvilValue',
    'magicNGUPowerBEvilValue',
    'magicNGUNumberEvilValue',
    'magicNGUTimeMachineEvilValue',
    'magicNGUEnergyNGUEvilValue',
    'magicNGUAdventureBEvilValue',

    'energyNGUAugmentsSadisticValue',
    'energyNGUWandoosSadisticValue',
    'energyNGURespawnSadisticValue',
    'energyNGUGoldSadisticValue',
    'energyNGUAdventureASadisticValue',
    'energyNGUPowerASadisticValue',
    'energyNGUDropChanceSadisticValue',
    'energyNGUMagicNGUSadisticValue',
    'energyNGUPPSadisticValue',
    'magicNGUYggdrasilSadisticValue',
    'magicNGUExpSadisticValue',
    'magicNGUPowerBSadisticValue',
    'magicNGUNumberSadisticValue',
    'magicNGUTimeMachineSadisticValue',
    'magicNGUEnergyNGUSadisticValue',
    'magicNGUAdventureBSadisticValue',
]

export var nguTargetElts = [
    'energyNGUAugmentsTarget',
    'energyNGUWandoosTarget',
    'energyNGURespawnTarget',
    'energyNGUGoldTarget',
    'energyNGUAdventureATarget',
    'energyNGUPowerATarget',
    'energyNGUDropChanceTarget',
    'energyNGUMagicNGUTarget',
    'energyNGUPPTarget',
    'magicNGUYggdrasilTarget',
    'magicNGUExpTarget',
    'magicNGUPowerBTarget',
    'magicNGUNumberTarget',
    'magicNGUTimeMachineTarget',
    'magicNGUEnergyNGUTarget',
    'magicNGUAdventureBTarget',

    'energyNGUAugmentsEvilTarget',
    'energyNGUWandoosEvilTarget',
    'energyNGURespawnEvilTarget',
    'energyNGUGoldEvilTarget',
    'energyNGUAdventureAEvilTarget',
    'energyNGUPowerAEvilTarget',
    'energyNGUDropChanceEvilTarget',
    'energyNGUMagicNGUEvilTarget',
    'energyNGUPPEvilTarget',
    'magicNGUYggdrasilEvilTarget',
    'magicNGUExpEvilTarget',
    'magicNGUPowerBEvilTarget',
    'magicNGUNumberEvilTarget',
    'magicNGUTimeMachineEvilTarget',
    'magicNGUEnergyNGUEvilTarget',
    'magicNGUAdventureBEvilTarget',

    'energyNGUAugmentsSadisticTarget',
    'energyNGUWandoosSadisticTarget',
    'energyNGURespawnSadisticTarget',
    'energyNGUGoldSadisticTarget',
    'energyNGUAdventureASadisticTarget',
    'energyNGUPowerASadisticTarget',
    'energyNGUDropChanceSadisticTarget',
    'energyNGUMagicNGUSadisticTarget',
    'energyNGUPPSadisticTarget',
    'magicNGUYggdrasilSadisticTarget',
    'magicNGUExpSadisticTarget',
    'magicNGUPowerBSadisticTarget',
    'magicNGUNumberSadisticTarget',
    'magicNGUTimeMachineSadisticTarget',
    'magicNGUEnergyNGUSadisticTarget',
    'magicNGUAdventureBSadisticTarget',
]

/*
topButtons
modeText
infoReq
extraReq

energyRow
MagicRow
totalSeconds

energyCapToMaxTargetRow
magicCapToMaxTargetRow

energyCapToMaxInDayRow
magicCapToMaxInDayRow
*/


