import { GameMode } from "./mode";
import Resource, { ResourceContainer } from "./resource";
import { Stat } from "./stat";

export class APItem extends Resource {}

export const APITEMLIST = [
    new APItem(0, 'energyPotionA', 'Energy Potion α', GameMode.ALL, 0, [[Stat.ENERGY_POWER, 100]]),
    new APItem(1, 'energyPotionB', 'Energy Potion β', GameMode.ALL, 0, [[Stat.ENERGY_POWER, 100]]),
    new APItem(2, 'energyPotionD', 'Energy Potion δ', GameMode.ALL, 0, [[Stat.ENERGY_POWER, 100]]),
    new APItem(3, 'magicPotionA', 'Magic Potion α', GameMode.ALL, 0, [[Stat.MAGIC_POWER, 100]]),
    new APItem(4, 'magicPotionB', 'Magic Potion β', GameMode.ALL, 0, [[Stat.MAGIC_POWER, 100]]),
    new APItem(5, 'magicPotionD', 'Magic Potion δ', GameMode.ALL, 0, [[Stat.MAGIC_POWER, 100]]),
    new APItem(6, 'resource3PotionA', 'Resource 3 Potion α', GameMode.ALL, 0, [[Stat.RES3_POWER, 200]]),
    new APItem(7, 'resource3PotionB', 'Resource 3 Potion β', GameMode.ALL, 0, [[Stat.RES3_POWER, 100]]),
    new APItem(8, 'resource3PotionD', 'Resource 3 Potion δ', GameMode.ALL, 0, [[Stat.RES3_POWER, 200]]),
    new APItem(9, 'energyBarBar', 'Energy Bar Bar', GameMode.ALL, 0, [[Stat.ENERGY_BARS, 100]]),
    new APItem(10, 'magicBarBar', 'Magic Bar Bar', GameMode.ALL, 0, [[Stat.MAGIC_BARS, 100]]),
    new APItem(11, 'macGuffinMuffin', 'MacGuffin Muffin', GameMode.ALL, 0, []),
    new APItem(12, 'icarusProudbottomsHomemadeFertilizer', ' Icarus Proudbottoms Homemade Fertilizer', GameMode.ALL, 0, []),
    new APItem(13, 'littleBluePill', 'Little Blue Pill', GameMode.ALL, 0, []), // Doubles your [[PP]] gain from [[ITOPOD]]. Each pill last for one kill.);
    new APItem(14, 'beastButter', 'Beast Butter', GameMode.ALL, 0, []), // Doubles your [[QP]] reward on your next [[Questing|quest]].);
    new APItem(15, 'luckyCharm', 'Lucky Charm', GameMode.ALL, 0, [[Stat.DROP_CHANCE, 100]]),
    new APItem(16, 'superLuckyCharm', 'Super Lucky Charm', GameMode.ALL, 0, [[Stat.DROP_CHANCE, 100]]),
    new APItem(17, 'mayoInfuser', 'Mayo Infuser', GameMode.ALL, 0, [[Stat.MAYO_SPEED, 100]]),
    new APItem(18, 'regularBlackPens', 'Regular Black Pens', GameMode.ALL, 0, []), // Adds 2 tiers to the next card spawned. Cannot be turned off.);
    new APItem(19, 'improvedLootFilter', 'Improved Loot Filter', GameMode.ALL, 0, []),
    new APItem(20, 'extraInventorySpace', 'Extra Inventory Space', GameMode.ALL, 0, []),
    new APItem(21, 'autoMergeandBoostTimers', '1/2 Auto Merge and Boost Timers!', GameMode.ALL, 0, []),
    new APItem(22, 'instaTrainingCap', 'Insta Training Cap', GameMode.ALL, 0, []),
    new APItem(23, 'customEnergy/Magic%Buttons', 'Custom Energy/Magic % Buttons', GameMode.ALL, 0, []),
    new APItem(24, 'moreCustomEnergy/Magic%Buttons', 'More Custom Energy/Magic % Buttons', GameMode.ALL, 0, []),
    new APItem(25, 'yggdrasilHarvestLight', ' Yggdrasil Harvest Light', GameMode.ALL, 0, []),
    new APItem(26, '7DayTimeBankforDailySpin', '7-Day Time Bank for Daily Spin!', GameMode.ALL, 0, []),
    new APItem(27, 'loadoutSlot', 'Loadout Slot!', GameMode.ALL, 0, []),
    new APItem(28, 'anExtraBeardSlot', 'An Extra Beard Slot!', GameMode.ALL, 0, []),
    new APItem(29, 'filterBoostsintoInfinityCube', 'Filter Boosts into Infinity Cube!', GameMode.ALL, 0, []),
    new APItem(30, 'lazyITOPODFloorShifter', 'Lazy ITOPOD Floor Shifter', GameMode.ALL, 0, []),
    new APItem(31, 'extraAccessorySlot', 'Extra Accessory Slot!', GameMode.ALL, 0, []),
    new APItem(32, 'daycareSpeedBoost', 'Daycare Speed Boost!', GameMode.ALL, 0, [[Stat.DAYCARE_TIME, 10]]),
    new APItem(33, 'anotherExtraAccessorySlot', 'Another Extra Accessory Slot!', GameMode.ALL, 0, []),
    new APItem(34, 'diggerSlots', 'Digger Slots!', GameMode.ALL, 0, []),
    new APItem(35, 'aMacGuffinSlot', 'A MacGuffin Slot!', GameMode.ALL, 0, []),
    new APItem(36, 'questReminder', 'Quest Reminder!', GameMode.ALL, 0, []),
    new APItem(37, 'fasterQuesting', 'Faster Questing!', GameMode.ALL, 0, []),
    new APItem(38, 'extendedQuestBank', 'Extended Quest Bank', GameMode.ALL, 0, []),
    new APItem(39, 'anotherExtraAccessorySlot2', 'Another Extra Accessory Slot!', GameMode.ALL, 0, []),
    new APItem(40, 'customIdleEnergyMagicButtons', 'Custom Idle Energy/Magic % Buttons!', GameMode.ALL, 0, []),
    new APItem(41, 'autoNuker', 'Auto Nuker', GameMode.ALL, 0, []),
    new APItem(42, 'yetAnotherExtraAccessorySlot', 'Yet Another Extra Accessory Slot!', GameMode.ALL, 0, []),
    new APItem(43, 'nGUCapModifier', 'NGU Cap Modifier', GameMode.ALL, 0, []),
    new APItem(44, 'daycareKittyArt', 'Daycare Kitty Art!', GameMode.ALL, 0, []),
    new APItem(45, 'customResource3Button', 'Custom Resource 3 % Button!', GameMode.ALL, 0, []),
    new APItem(46, 'anotherCustomResource3Button', 'Another Custom Resource 3 % Button!', GameMode.ALL, 0, []),
    new APItem(47, 'customIdleResource3Button', 'Custom Idle Resource 3 % Button!', GameMode.ALL, 0, []),
    new APItem(48, 'resource3NameRandomizer', 'Resource 3 Name Randomizer', GameMode.ALL, 0, []),
    new APItem(49, 'fasterWishes', 'Faster Wishes', GameMode.ALL, 0, [[Stat.WISH_SPEED, 25]]),
    new APItem(50, 'inventoryMergeSlots', 'Inventory Merge Slots', GameMode.ALL, 0, []),
    new APItem(51, 'adventureLight', 'Adventure Light', GameMode.ALL, 0, []),
    new APItem(52, 'adventureAdvancer', 'Adventure Advancer', GameMode.ALL, 0, []),
    new APItem(53, 'goToQuestZoneButton', 'Go To Quest Zone Button', GameMode.ALL, 0, []),
    new APItem(54, 'anEvilAccessorySlot', ' An Evil Accessory Slot', GameMode.ALL, 0, []),
    new APItem(55, 'extraDeckSize', 'Extra Deck Size!', GameMode.ALL, 0, []),
    new APItem(56, 'mayoGenerator', 'Mayo Generator', GameMode.ALL, 0, [[Stat.MAYO_GENERATOR, 2]]),
    new APItem(57, 'extraTagSlot', 'Extra Tag Slot!', GameMode.ALL, 0, []),
    new APItem(58, 'extraAccessorySlot2', 'Extra Accessory Slot', GameMode.ALL, 0, []),
    new APItem(59, 'redHeart', 'My Red Heart &lt;3', GameMode.ALL, 0, []),
    new APItem(60, 'yellowHeart', 'My Yellow Heart &lt;3', GameMode.ALL, 0, []),
    new APItem(61, 'brownHeart', 'My Brown Heart &lt;3', GameMode.ALL, 0, []),
    new APItem(62, 'greenHeart', 'My Green Heart &lt;3', GameMode.ALL, 0, []),
    new APItem(63, 'blueHeart', 'My Blue Heart &lt;3', GameMode.ALL, 0, []),
    new APItem(64, 'purpleHeart', 'My Purple Heart &lt;3', GameMode.ALL, 0, []),
    new APItem(65, 'orangeHeart', 'My Orange Heart &lt;3', GameMode.ALL, 0, []),
    new APItem(66, 'greyHeart', 'My Grey Heart &lt;3', GameMode.ALL, 0, []),
    new APItem(67, 'pinkHeart', 'My Pink Heart &lt;3', GameMode.ALL, 0, []),
    new APItem(68, 'rainbowHeart', 'My Rainbow Heart &lt;3', GameMode.ALL, 0, []),
    new APItem(69, '200EXP', '200 EXP!', GameMode.ALL, 0, []),
    new APItem(70, '500EXP', '500 EXP!', GameMode.ALL, 0, []),
    new APItem(71, '2000EXP', '2000 EXP!', GameMode.ALL, 0, []),
    new APItem(72, '25PP', ' 25 PP!', GameMode.ALL, 0, []),
    new APItem(73, '100PP', '100 PP!', GameMode.ALL, 0, []),
    new APItem(74, '500PP', '500 PP!', GameMode.ALL, 0, []),
];

export var APITEMS = new ResourceContainer(APITEMLIST);