import { Stat } from "./stat"
import Resource, { ResourceContainer } from "./resource"

export class Perk extends Resource{}


export const PERKLIST = [
    new Perk(0, 'The Newbie Energy Perk', 1, []), // Added to base energy
    new Perk(1, 'The Newbie Magic Perk', 1, []), // Added to base magic
    new Perk(2, 'The Newbie Adventure Perk', 1, [[Stat.POWER, 10]]), 
    new Perk(3, 'The Newbie Drop Chance Perk', 1, [[Stat.DROP_CHANCE, 10],]),
    new Perk(4, 'The Newbie Stat Perk', 1, [
        [Stat.POWER, 100],
        [Stat.TOUGHNESS, 100],
    ]),
    new Perk(5, 'Stat Boost for Rich Perks I', 1, [
        [Stat.POWER, 10],
        [Stat.TOUGHNESS, 10],
    ]),
    new Perk(6, 'Generic Energy Power Perk I', 1, [[Stat.ENERGY_POWER, 1]]),
    new Perk(7, 'Generic Energy Bar Perk I', 1, [[Stat.ENERGY_BARS, 1]]),
    new Perk(8, 'Generic Energy Cap Perk I', 1, [[Stat.ENERGY_CAP, 1]]),
    new Perk(9, 'Generic Magic Power Perk I', 1, [[Stat.MAGIC_POWER, 1]]),
    new Perk(10, 'Generic Magic Bar Perk I', 1, [[Stat.MAGIC_BARS, 1]]),
    new Perk(11, 'Generic Magic Cap Perk I', 1, [[Stat.MAGIC_CAP, 1]]),
    new Perk(12, 'Boosted Boosts I', 1, []),
    new Perk(13, 'Faster NGU Energy', 1, [[Stat.ENERGY_NGU_SPEED, 2.5],]),
    new Perk(14, 'Faster NGU Magic', 1, [[Stat.MAGIC_NGU_SPEED, 2.5],]),
    new Perk(15, 'Double Basic Training', 1, []),
    new Perk(16, 'Quicker Power Fruit Beta Activation', 1, []),
    new Perk(17, 'Quicker Fruit of Numbers Bonus Activation', 1, []),
    new Perk(18, 'Instant Advanced Training Levels!', 1, []),
    new Perk(19, '"Fruit of Knowledge sucks, 1/5"', 1, []),
    new Perk(20, '"Fruit of Knowledge STILL sucks, 1/5"', 1, []),
    // new Perk(21, 'Five O'Clock Shadow', 1, [The time factor for Beard trimming conversion will grow faster with this fancy perk! The time factor will reach its maximum 1 hour sooner per level, to a minimum of 12 hours. This means more trimmings in less time!]),
    new Perk(22, 'Wandoos Lover', 1, []),
    new Perk(23, 'Golden Showers', 1, [[Stat.GOLD_DROP, 5]]),
    new Perk(24, 'I Want Your Seeds ;)', 1, [[Stat.SEED_GAIN, 5],]),
    // new Perk(25, 'The Loot Goblin's Blessing', 1, [Gain the blessings of a fat green loot goblin! With each level of this perk you gain a 1% chance that any item dropped at lvl 1 or higher gains +1 level! This stacks with the Gaudy Set Bonus.]),
    // new Perk(26, 'Improved Cube Boosting!', 1, [With this perk, boosts going into the cube convert at a 2% rate instead of 1%! Yaaaaaaay!]),
    // new Perk(27, 'Daycare Kitty's Blessing I', 1, [Make the Daycare kitty even happier, and she'll grow your daycare items 1% faster per level! :)]),
    // new Perk(28, 'Daycare Kitty's Blessing II', 1, [Make the Daycare kitty even MORE happier, and she'll grow your daycare items an additional 1% faster per level! :) :)]),
    // new Perk(29, 'You'll Really Want This', 1, [This perk awards a FREE accessory slot, pure and simple.]),
    // new Perk(30, 'What a Crappy Perk', 1, [This perk grants a tiny, tiny chance that the Pissed Off Dudes in the ITOPOD drop poop. It also works offline!]),
    // new Perk(31, 'More Inventory Space I', 1, [Gain an extra Inventory Space for each level of this perk!]),
    // new Perk(32, 'More Inventory Space II', 1, [Gain an extra Inventory Space for each level of this perk! Why does it cost 5x as much as the other perk? Listen kid, inventory space is a hot commodity right now, it's just business.]),
    // new Perk(33, 'Boosted Boosts II', 1, [Let's boost the boost to boosts some more, shall we? Each level of this perk adds a 2% stacking bonus to the total power of any applied boost!]),
    // new Perk(34, 'Bonus Titan EXP!', 1, [You like getting EXP from Titans? For each level of this perk, the first 3 kills of each titan, each rebirth will grant +50% extra EXP! WTF does this mean? For example: level 2 of this perk means the first 6 kills of each titan grants the 50% EXP bonus, every rebirth!]),
    // new Perk(35, 'Bonus Boss Exp!', 1, [You also like getting EXP from defeating Bosses? Well alright! This perk will grant a stacking +2% bonus to exp dropped by bosses 24 and on!]),
    // new Perk(36, 'Advanced Training Level [[Banks|Bank]] I', 1, [Each level in this perk saves 1% (rounded down) of your levels gained in Advanced Training when you rebirth, saving it for the next rebirth!]),
    // new Perk(37, 'Advanced Training Level Bank II', 1, [Each level in this perk saves 1% (rounded down) of your levels gained in Advanced Training when you rebirth, saving it for the next rebirth!]),
    // new Perk(38, 'Advanced Training Level Bank III', 1, [Each level in this perk saves 1% (rounded down) of your levels gained in Advanced Training when you rebirth, saving it for the next rebirth!]),
    // new Perk(39, 'Advanced Training Level Bank IV', 1, [Each level in this perk saves 1% (rounded down) of your levels gained in Advanced Training when you rebirth, saving it for the next rebirth!]),
    // new Perk(40, 'Advanced Training Level Bank V', 1, [Each level in this perk saves 1% (rounded down) of your levels gained in Advanced Training when you rebirth, saving it for the next rebirth!]),
    // new Perk(41, 'Time Machine Level Bank I', 1, [Each level in this perk saves 1% (rounded down) of your levels gained in Time Machine when you rebirth, saving it for the next rebirth!]),
    // new Perk(42, 'Time Machine Level Bank II', 1, [Each level in this perk saves 1% (rounded down) of your levels gained in Time Machine when you rebirth, saving it for the next rebirth!]),
    // new Perk(43, 'Time Machine Level Bank III', 1, [Each level in this perk saves 1% (rounded down) of your levels gained in Time Machine when you rebirth, saving it for the next rebirth!]),
    // new Perk(44, 'Time Machine Level Bank IV', 1, [Each level in this perk saves 1% (rounded down) of your levels gained in Time Machine when you rebirth, saving it for the next rebirth!]),
    // new Perk(45, 'Time Machine Level Bank V', 1, [Each level in this perk saves 1% (rounded down) of your levels gained in Time Machine when you rebirth, saving it for the next rebirth!]),
    // new Perk(46, 'Beard Temp Level Bank I', 1, [Each level in this perk saves 1% (rounded down) of the temp Beard Levels you've gained when you rebirth, saving it for the next rebirth!]),
    // new Perk(47, 'Beard Temp Level Bank II', 1, [Each level in this perk saves 1% (rounded down) of the temp Beard Levels you've gained when you rebirth, saving it for the next rebirth!]),
    // new Perk(48, 'Beard Temp Level Bank III', 1, [Each level in this perk saves 1% (rounded down) of the temp Beard Levels you've gained when you rebirth, saving it for the next rebirth!]),
    // new Perk(49, 'Beard Temp Level Bank IV', 1, [Each level in this perk saves 1% (rounded down) of the temp Beard Levels you've gained when you rebirth, saving it for the next rebirth!]),
    // new Perk(50, 'Beard Temp Level Bank V', 1, [Each level in this perk saves 1% (rounded down) of the temp Beard Levels you've gained when you rebirth, saving it for the next rebirth!]),
    // new Perk(51, 'The First Harvest's The Best', 1, [Each level in this perk will grant a +10% bonus to the first eaten or harvested fruit for all fruits each rebirth!]),
    // new Perk(52, 'A Digger Slot!', 1, [Unlock an additional Digger Slot for the Gold Diggers Feature!]),
    // new Perk(53, 'Ooh, Another Digger Slot!', 1, [Unlock yet another Digger Slot for the Gold Diggers Feature!]),
    // new Perk(54, 'Stat Boost for Rich Perks II', 1, [For the truly Richest of Jerks. Gain +1% Attack/Defence per level of this perk!]),
    // new Perk(55, 'Adventure Boost For Rich Perks I', 1, [For the truly Richest of Jerks. Gain +0.1% to Adventure Stats per level of this perk!]),
    // new Perk(56, 'Macguffin Daycare!', 1, [With this perk, the Daycare Kitty can use her power of happiness to improve your ancient cosmic artifacts! c:]),
    // new Perk(57, 'Generic Energy Power Perk II', 1, [Each level grants +1% bonus multiplier to your Energy Power!]),
    // new Perk(58, 'Generic Energy Bar Perk II', 1, [Each level grants +1% bonus multiplier to your Energy Bars!]),
    // new Perk(59, 'Generic Energy Cap Perk II', 1, [Each level grants +1% bonus multiplier to your Energy Cap!]),
    // new Perk(60, 'Generic Magic Power Perk II', 1, [Each level grants +1% bonus multiplier to your Magic Power!]),
    // new Perk(61, 'Generic Magic Bar Perk II ', 1, [Each level grants +1% bonus multiplier to your Magic Bars!]),
    // new Perk(62, 'Generic Magic Cap Perk II', 1, [Each level grants +1% bonus multiplier to your Magic Cap!]),
    // new Perk(63, 'Faster NGU Energy II', 1, [Raises the Speed of Energy-based NGU's by 2% per level!]),
    // new Perk(64, 'Faster NGU Magic II', 1, [Raises the Speed of Magic-based NGU's by 2% per level!]),
    // new Perk(65, 'Improved Macguffin Drops I', 1, [Improve the base level of all MacGuffin drops by 1!]),
    // new Perk(66, 'A MacGuffin Slot!', 1, [Gain an additional MacGuffin Slot!]),
    // new Perk(67, 'Another MacGuffin Slot!', 1, [Gain another additional MacGuffin Slot!]),
    // new Perk(68, 'MacGuffin ITOPOD Drops!', 1, [This will unlock MacGuffin drops in the ITOPOD! Every 5000 kills, you'll obtain a random MacGuffin!]),
    // new Perk(69, 'Improved MacGuffin ITOPOD Drops I', 1, [Reduce the number of kills per MacGuffin drop in the ITOPOD by 20%!]),
    // new Perk(70, 'Improved MacGuffin ITOPOD Drops II', 1, [Reduce the number of kills per MacGuffin drop in the ITOPOD by another 25%!]),
    // new Perk(71, 'Improved MacGuffin ITOPOD Drops III', 1, [Reduce the number of kills per MacGuffin drop in the ITOPOD by another 25%!]),
    // new Perk(72, 'Blood Macguffin α Spell!', 1, [Unlocks the Blood Macguffin α Spell, which can raise the level of a random equipped Macguffin!]),
    // new Perk(73, 'Blood Macguffin β Spell!', 1, [Unlocks the Blood Macguffin β Spell, which can raise the level of ALL equipped Macguffins!]),
    // new Perk(74, 'Generic Energy Power Perk III', 1, [Each level grants +0.3% bonus multiplier to your Energy Power!]),
    // new Perk(75, 'Generic Energy Bar Perk III', 1, [Each level grants +0.3% bonus multiplier to your Energy Bars!]),
    // new Perk(76, 'Generic Energy Cap Perk III', 1, [Each level grants +0.3% bonus multiplier to your Energy Cap!]),
    // new Perk(77, 'Generic Magic Power Perk III', 1, [Each level grants +0.3% bonus multiplier to your Magic Power!]),
    // new Perk(78, 'Generic Magic Bar Perk III', 1, [Each level grants +0.3% bonus multiplier to your Magic Bars!]),
    // new Perk(79, 'Generic Magic Cap Perk III', 1, [Each level grants +0.3% bonus multiplier to your Magic Cap!]),
    // new Perk(80, 'Faster NGU Energy III', 1, [Raises the Speed of Energy-based NGU's by 0.3% per level!]),
    // new Perk(81, 'Faster NGU Magic III', 1, [Raises the Speed of Magic-based NGU's by 0.3% per level!]),
    // new Perk(82, 'Stat Boost for Rich Perks III', 1, [For the really, truly Richest of Jerks. Gain +1% to Attack/Defence per level of this perk!]),
    // new Perk(83, 'Adventure Boost For Rich Perks II', 1, [For the really, truly Richest of Jerks. Gain +0.1% to Adventure stats per level of this perk!]),
    // new Perk(84, '"Iron Pill Also Sucks 1/5"', 1, [Iron Pill yields +5x more stats per level of this perk, up to 26x at level 5!]),
    // new Perk(85, '"Iron Pill Still Sucks 1/5"', 1, [Iron Pill yields +1x more stats per level of this perk, up to 4x at level 3!]),
    // new Perk(86, 'Daycare Slot! c:', 1, [Make the Daycare Kitty even happier-er-er-est-er and get a new Daycare Slot!]),
    // new Perk(87, 'Not So Minor Anymore', 1, [The base Minor Quest reward modifier is increased by 2 with this perk! Normally this value is 10.]),
    // new Perk(88, 'Another MacGuffin Slot!', 1, [Gain an additional MacGuffin Slot! What were you expecting, a yacht?]),
    // new Perk(89, 'Better QP Rewards!', 1, [Each level in this Perk will improve QP reward by 0.2%!]),
    // new Perk(90, 'Improved Quest Looting', 1, [Each level in this Perk will improve the drop chance for Quest Items by 0.5%]),
    // new Perk(91, 'Advanced Gooder Idle Questing', 1, [This perk will reduce the speed divider placed on Idle Questing by 1! Normally, this divider is 8.]),
    // new Perk(92, 'Even More Advanced Gooder Idle Questing', 1, [This perk will reduce the speed divider placed on Idle Questing by another 1! Normally, this divider is 8.]),
    // new Perk(93, 'SPAWN FASTER DAMMIT', 1, [Each level of this perk reduces normal enemy respawn times by 0.1%.]),
    // new Perk(94, '[[Fibonacci Perk|The Fibonacci Perk]]', 1, [A very special perk: When the level of this perk reaches the next number in the Fibonacci sequence, you get a new [[Fibonacci Perk|secret perk]]!  (Until it inevitably gets spoiled on the Discord or Wiki)]),
    // new Perk(95, 'Generic Resource 3 Power Perk I', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Power! I wonder what you named it.]),
    // new Perk(96, 'Generic Resource 3 Bar Perk I', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Bars! I wonder what you named it.]),
    // new Perk(97, 'Generic Resource 3 Cap Perk I', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Cap! I wonder what you named it.]),
    // new Perk(98, 'Generic Resource 3 Power Perk II', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Power! I wonder what you named it.]),
    // new Perk(99, 'Generic Resource 3 Bar Perk II', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Bars! I wonder what you named it.]),
    // new Perk(100, 'Generic Resource 3 Cap Perk II ', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Cap! I wonder what you named it.]),
    // new Perk(101, 'Generic Resource 3 Power Perk III', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Power! I wonder what you named it.]),
    // new Perk(102, 'Generic Resource 3 Bar Perk III ', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Bars! I wonder what you named it.]),
    // new Perk(103, 'Generic Resource 3 Cap Perk III', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Cap! I wonder what you named it.]),
    // new Perk(104, 'Truly Idle Questing', 1, [With this Perk, Idle Quests will automatically be handed in, and a new Quest started!]),
    // new Perk(105, 'Gooder Idle Questing', 1, [This perk will reduce the speed divider placed on Idle Questing by 2! Normally, this divider is 8.]),
    // new Perk(106, 'Another Gooder Idle Questing', 1, [This perk will reduce the speed divider placed on Idle Questing by 1! Normally, this divider is 8.]),
    // new Perk(107, 'Boosted Boosts III ', 1, [Boostception is here. Each level of this perk adds a 2% stacking bonus to the total boost power of any applied boost!]),
    // new Perk(108, 'Faster Wishes I', 1, [So you just got WIshes and hate how slow they are. Each level of this perk will grant 0.2% wish speed to help alleviate that issue.]),
    // new Perk(109, 'Minimum Wish Time Reduction I', 1, [Got your resources pumped into Wishes so fast, the Fairies can't work any faster? This perk will whip them into shape! Each level reduces the minimum wish completion time by 24 seconds. This time is normally 4 hours.]),
    // new Perk(110, 'Minimum Wish Time Reduction II', 1, [With this perk,you can work wishes so efficiently that all the labour can be done by a single Australian man in record time! Reduces the minimum wish timer by an additional 24 seconds per level of this perk.]),
    // new Perk(111, 'An Inventory Merge Slot', 1, [Convert a slot in your inventory into an inventory [[Adventure_Mode_Equipment#Automerge_slots|Automerge Slot]]! This slot will be triggered by the Automerge function - handy for levelling up gear automatically!]),
    // new Perk(112, 'Another Inventory Merge Slot', 1, [Unlock another Inventory Automerge Slot!]),
    // new Perk(113, 'Adventure Hack Milestone Reduces I', 1, [Each level of this perk reduces the number of hack levels required per milestone by 1! This means more milestone bonuses!]),
    // new Perk(114, 'Blood Hack Milestone Reduces I', 1, [Each level of this perk reduces the number of hack levels required per milestone by 1! This means more milestone bonuses!]),
    // new Perk(115, 'Daycare Hack Milestone Reduces I', 1, [Each level of this perk reduces the number of hack levels required per milestone by 1! This means more milestone bonuses!]),
    // new Perk(116, 'Generic Energy Power Perk IV', 1, [Each level grants +0.2% bonus multiplier to your Energy Power!]),
    // new Perk(117, 'Generic Energy Bar Perk IV', 1, [Each level grants +0.2% bonus multiplier to your Energy Bars!]),
    // new Perk(118, 'Generic Energy Cap Perk IV', 1, [Each level grants +0.2% bonus multiplier to your Energy Cap!]),
    // new Perk(119, 'Generic Magic Power Perk IV', 1, [Each level grants +0.2% bonus multiplier to your Magic Power!]),
    // new Perk(120, 'Generic Magic Bar Perk IV', 1, [Each level grants +0.2% bonus multiplier to your Magic Bars!]),
    // new Perk(121, 'Generic Magic Cap Perk IV', 1, [Each level grants +0.2% bonus multiplier to your Magic Cap!]),
    // new Perk(122, 'Generic Resource 3 Power Perk IV', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Power! I wonder what you named it.]),
    // new Perk(123, 'Generic Resource 3 Bar Perk IV', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Bars! I wonder what you named it.]),
    // new Perk(124, 'Generic Resource 3 Cap Perk IV', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Cap! I wonder what you named it.]),
    // new Perk(125, 'Welcome to Evil Difficulty', 1, [Evil Difficulty kicking your ass? There there, buddy. Take this perk and receive a +200% buff to Attack/Defense and 50% Drop Chance bonus. It'll be okay.]),
    // new Perk(126, 'Generic Energy Power Perk V', 1, [Each level grants +0.2% bonus multiplier to your Energy Power! Why is it lower? Because in Sadistic Difficulty I don't give a crap about you!]),
    // new Perk(127, 'Generic Energy Bar Perk V', 1, [Each level grants +0.1% bonus multiplier to your Energy Bars!]),
    // new Perk(128, 'Generic Energy Cap Perk V', 1, [Each level grants +0.1% bonus multiplier to your Energy Cap!]),
    // new Perk(129, 'Generic Magic Power Perk V', 1, [Each level grants +0.2% bonus multiplier to your Magic Power!]),
    // new Perk(130, 'Generic Magic Bar Perk V', 1, [Each level grants +0.1% bonus multiplier to your Magic Bars!]),
    // new Perk(131, 'Generic Magic Cap Perk V', 1, [Each level grants +0.1% bonus multiplier to your Magic Cap!]),
    // new Perk(132, 'Generic Resource 3 Power Perk V', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Power! I wonder what you named it.]),
    // new Perk(133, 'Generic Resource 3 Bar Perk V', 1, [Each level grants +0.5% bonus multiplier to your 3rd Resource's Bars! I wonder what you named it.]),
    // new Perk(134, 'Generic Resource 3 Cap Perk V', 1, [Each level grants +0.5% bonus multiplier to your 3rd Resource's Cap! I wonder what you named it.]),
    // new Perk(135, 'Generic Energy Power Perk VI', 1, [Each level grants +0.2% bonus multiplier to your Energy Power!]),
    // new Perk(136, 'Generic Energy Bar Perk VI', 1, [Each level grants +0.1% bonus multiplier to your Energy Bars!]),
    // new Perk(137, 'Generic Energy Cap Perk VI', 1, [Each level grants +0.1% bonus multiplier to your Energy Cap!]),
    // new Perk(138, 'Generic Magic Power Perk VI', 1, [Each level grants +0.2% bonus multiplier to your Magic Power!]),
    // new Perk(139, 'Generic Magic Bar Perk VI', 1, [Each level grants +0.1% bonus multiplier to your Magic Bars!]),
    // new Perk(140, 'Generic Magic Cap Perk VI', 1, [Each level grants +0.1% bonus multiplier to your Magic Cap!]),
    // new Perk(141, 'Generic Resource 3 Power Perk VI', 1, [Each level grants +1% bonus multiplier to your 3rd Resource's Power! I wonder what you named it.]),
    // new Perk(142, 'Generic Resource 3 Bar Perk VI', 1, [Each level grants +0.5% bonus multiplier to your 3rd Resource's Bars! I wonder what you named it.]),
    // new Perk(143, 'Generic Resource 3 Cap Perk VI', 1, [Each level grants +0.5% bonus multiplier to your 3rd Resource's Cap! I wonder what you named it.]),
    // new Perk(144, 'Welcome to Sadistic Difficulty', 1, [Getting your ass kicked by Sadistic? Maybe this will help. Receive a 1000% Bonus to Attack/Defense, 15% to Adventure Stats, 20% Aug Speed bonus, and 20% NGU Speed Bonus]),
    // new Perk(145, 'Bonus Quest Handin Progess I', 1, [You can now hand in higher level Quest Items for added progress. The formula is 1 + (level/10) progress, rounded down.]),
    // new Perk(146, 'Bonus Quest Handin Progess II', 1, [Reduce the level ratio for higher level Quest handins by 1 per level of this Perk! Originally the formula is 1 + (level/10), rounded down.]),
    // new Perk(147, 'Improved Major Quest QP Rewards', 1, [Each level adds + 1 to Major Quests' Base QP! Normally this is 50.]),
    // new Perk(148, 'Improved Minor Quest QP Rewards', 1, [Each level adds + 1 to Minor Quests' Base QP! Normally this is 10.]),
    // new Perk(149, 'Stat Boost for rich Perks IV', 1, [For the really, truly Richest of Jerks. Gain +1% to Attack/Defence per level of this perk!]),
    // new Perk(150, 'Adventure Boost For Rich Perks III', 1, [For the really, truly Richest of Jerks. Gain +0.05% to Adventure stats per level of this perk!]),
    // new Perk(151, 'Stat Boost for rich Perks V', 1, [For the really, really truly Richest of Jerks. Gain +1% to Attack/Defence per level of this perk!]),
    // new Perk(152, 'Adventure Boost For Rich Perks IV', 1, [For the really, really truly Richest of Jerks. Gain +0.05% to Adventure stats per level of this perk!]),
    // new Perk(153, 'Stat Boost for rich Perks VI', 1, [For the really, really, really, truly Richest of Jerks. Gain +1% to Attack/Defence per level of this perk!]),
    // new Perk(154, 'Adventure Boost For Rich Perks V', 1, [For the really, really, really, truly Richest of Jerks. Gain +0.05% to Adventure stats per level of this perk!]),
    // new Perk(155, 'Faster Wishes II', 1, [Each level of this perk will add +0.1% to wish speed!]),
    // new Perk(156, 'Faster Wishes III', 1, [Each level of this perk will add +0.1% to wish speed!]),
    // new Perk(157, 'Improved Sadistic Boss Multiplier I', 1, [Each level of this perk adds +0.0005 to the Sadistic Boss Multiplier. Originally this value is 1.20. A tiny change in this number has a huge difference!]),
    // new Perk(158, 'Improved Sadistic Boss Multiplier II', 1, [Each level of this perk adds another +0.0005 to the Sadistic Boss Multiplier. Originally this value is 1.20. A tiny change in this number has a huge difference! ]),
    // new Perk(159, 'Faster Wishes IV', 1, [Each level of this perk will add +0.1% to wish speed!]),
    // new Perk(160, 'Faster Wishes V', 1, [Each level of this perk will add +0.1% to wish speed!]),
    // new Perk(161, 'Augment Card Tier Up I', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(162, 'Gold Drop Card Tier Up I', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(163, 'Wishes Card Tier Up I', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(164, 'A/D Card Tier Up I', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(165, 'Magic NGU Card Tier Up I', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(166, 'TM Card Tier Up I', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(167, 'QP Card Tier Up I', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(168, 'Daycare Card Tier Up I', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(169, 'Energy NGU Card Tier Up I', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(170, 'Drop Chance Card Tier Up I', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(171, 'Wandoos Card Tier Up I', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(172, 'Adventure Stats Card Tier Up I', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(173, 'Hacks Card Tier Up I', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(174, 'Augment Card Tier Up II', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(175, 'Gold Drop Card Tier Up II', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(176, 'Wishes Card Tier Up II', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(177, 'A/D Card Tier Up II', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(178, 'Magic NGU Card Tier Up II', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(179, 'TM Card Tier Up II', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(180, 'QP Card Tier Up II', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(181, 'Daycare Card Tier Up II', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(182, 'Energy NGU Card Tier Up II', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(183, 'Drop Chance Card Tier Up II', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(184, 'Wandoos Card Tier Up II', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(185, 'Adventure Stats Card Tier Up II', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(186, 'Hacks Card Tier Up II', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(187, 'Augment Card Tier Up III', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(188, 'Gold Drop Card Tier Up III', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(189, 'Wishes Card Tier Up III', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(190, 'A/D Card Tier Up III', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(191, 'Magic NGU Card Tier Up III', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(192, 'TM Card Tier Up III', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(193, 'QP Card Tier Up III', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(194, 'Daycare Card Tier Up III', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(195, 'Energy NGU Card Tier Up III', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(196, 'Drop Chance Card Tier Up III', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(197, 'Wandoos Card Tier Up III', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(198, 'Adventure Stats Card Tier Up III', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(199, 'Hacks Card Tier Up III', 1, [This perk will raise the Tier of all cards with this bonus type by 1!]),
    // new Perk(200, 'Faster Card Generation I', 1, [Increase Card Generation Speed by 0.5% for each level of this Perk!]),
    // new Perk(201, 'Faster Mayo Generation I', 1, [Increase Mayo Generation Speed by 0.5% for each level of this Perk!]),
    // new Perk(202, 'Faster Card Generation II', 1, [Increase Card Generation Speed by 0.4% for each level of this Perk!]),
    // new Perk(203, 'Faster Mayo Generation II', 1, [Increase Mayo Generation Speed by 0.4% for each level of this Perk!]),
    // new Perk(204, 'Faster Card Generation III', 1, [Increase Card Generation Speed by 0.3% for each level of this Perk!]),
    // new Perk(205, 'Faster Mayo Generation III', 1, [Increase Mayo Generation Speed by 0.3% for each level of this Perk!]),
    // new Perk(206, 'Faster Card Generation IV', 1, [Increase Card Generation Speed by 0.3% for each level of this Perk!]),
    // new Perk(207, 'Faster Mayo Generation IV', 1, [Increase Mayo Generation Speed by 0.3% for each level of this Perk!]),
    // new Perk(208, 'Bigger Deck Size I', 1, [This Perk increases your max Deck size by 1 per level!]),
    // new Perk(209, 'Bigger Deck Size II', 1, [This Perk increases your max Deck size by an additional 1 per level!]),
    // new Perk(210, 'Bigger Deck Size III', 1, [This Perk increases your max Deck size by an additional 1 per level!]),
    // new Perk(211, 'Extra Mayo Generator!', 1, [This Perk grants an extra Mayo Generator Slot! There's also a 2% Mayo Speed bonus for no reason!]),
    // new Perk(212, 'Better Tags I', 1, [This Perk improves the effects of tagging by 0.05% per level!]),
    // new Perk(213, 'Better Tags II', 1, [This Perk improves the effects of tagging by 0.04% per level!]),
    // new Perk(214, 'Better Tags III', 1, [This Perk improves the effects of tagging by 0.04% per level!]),
    // new Perk(215, 'Better Tags IV', 1, [This Perk improves the effects of tagging by 0.04% per level!]),
    // new Perk(216, 'Card Recycling: Card Spawn', 1, [With this Card Recycling Perk, we'll chuck your yeeted cards into a Blendomatic 5000, which somehow advances your card spawn timer by 10%! If you recycle a BIG CHONKER, the timer for your BIG CHONKER card will advance by 25%!]),
    // new Perk(217, 'Drop Chance Hack Milestone Reducer I', 1, [Each level of this perk reduces the number of hack levels required per milestone by 1! This means more milestone bonuses!]),
    // new Perk(218, 'Augments Hack Milestone Reducer I', 1, [Each level of this perk reduces the number of hack levels required per milestone by 1! This means more milestone bonuses!]),
    // new Perk(219, 'Magic NGU Hack Milestone Reducer I', 1, [Each level of this perk reduces the number of hack levels required per milestone by 1! This means more milestone bonuses!]),
    // new Perk(220, 'The Final Generic Energy Power Perk', 1, [Eh, just go nuts with this one. Gain 1% Power per level]),
    // new Perk(221, 'The Final Generic Energy Bar Perk', 1, [Eh, just go nuts with this one. Gain 1% Bars per level]),
    // new Perk(222, 'The Final Generic Energy Cap Perk', 1, [Eh, just go nuts with this one. Gain 1% Cap per level]),
    // new Perk(223, 'The Final Generic Magic Power Perk', 1, [Eh, just go nuts with this one. Gain 1% Power per level]),
    // new Perk(224, 'The Final Generic Magic Bar Perk', 1, [Eh, just go nuts with this one. Gain 1% Bars per level]),
    // new Perk(225, 'The Final Generic Magic Cap Perk', 1, [Eh, just go nuts with this one. Gain 1% Cap per level]),
    // new Perk(226, 'The Final Generic Resource 3 Power Perk', 1, [Eh, just go nuts with this one. Gain 1% Power per level]),
    // new Perk(227, 'The Final Generic Resource 3 Bar Perk', 1, [Eh, just go nuts with this one. Gain 1% Bars per level]),
    // new Perk(228, 'The Final Generic Resource 3 Cap Perk', 1, [Eh, just go nuts with this one. Gain 1% Cap per level]),
    // new Perk(229, 'Boosted Boosts IV', 1, [Each level of this perk adds a 1% stacking bonus to the total boost power of any applied boost!]),
    // new Perk(230, 'Boosted Boosts V', 1, [Each level of this perk adds another 1% stacking bonus to the total boost power of any applied boost!]),
    // new Perk(231, 'ERROR', 1, [NGU.EXE HAS ENCOUNTERED AN ERROR AND MUST CLOSE]),
]

export var PERKS = new ResourceContainer(PERKLIST.map((perk) => {
    return [perk.id, perk];
}));